anguage: php

php:
  - 7.2
matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - mkdir vendor/orchestra/testbench-core/laravel/app/Http
  - mkdir vendor/orchestra/testbench-core/laravel/app/Http/Livewire

script:
  - phpunit
  
